ruby on rails/config/routes.rb
Sportbook::Application.routes.draw do

  ####################
  # routs for db (using sportdb-admin rails engine)

  puts '[boot] routes.rb - before mount SportDbAdmin::Engine'
  mount SportDbAdmin::Engine, :at => '/db'
  puts '[boot] routes.rb - after mount SportDbAdmin::Engine'


  puts '[boot] routes.rb - before mount WorldDbAdmin::Engine'
  mount WorldDbAdmin::Engine, :at => '/worlddb'
  puts '[boot] routes.rb - after mount WorldDbAdmin::Engine'


  mount About::Server,     :at => '/sys'
  mount DbBrowser::Server, :at => '/browse'

  ## todo: add ActivityDb::Server too


  get 'signin',   :to => 'sessions#new'
  get 'signout',  :to => 'sessions#destroy'

  get 'about',    :to => 'pages#about'
  get 'home',     :to => 'pages#home'
  get 'style',    :to => 'pages#style'     # testpage for styles (css)

  get 'live',          :to => 'live#index'
  get 'live/:game_id', :to => 'live#show', :as => :live_game

  get 'time',             :to => 'time#index'
  get 'time2',            :to => 'time#index2'
  get 'time3',            :to => 'time#index3'   # old action timeline - obsolete remove/delete after cleanup!!
  get 'time4',            :to => 'time#index4'   # old action timeline - obsolete remove/delete after cleanup!!

  get 'ical/:play_id',   :to => 'ical#index'

  resource :session, :only => [:new, :create, :destroy]

  resource :password, :only => [:new, :create, :destroy]

  resources :profiles, :only => [:index, :show]

  resources :plays

  resources :pools do
    get 'add_player_to', :on => :member
    resources :players, :only => [:show, :edit]
  end

  #############
  # routes for admin

  get 'admin',  :to => 'admin/pools#index'
  
  namespace :admin do
    resources :pools

    # add plain text import forms for fixtures n quotes  
    resources :fixtures
    resources :quotes    
    
    get 'bonus',         :to => 'bonus#index'

    ## fix: post required?? double check!!
    get 'bonus/update',  :to => 'bonus#update'
  end

  ##############################
  # routes for admin via module (admin not in url -- todo/fix)
  
  scope :module => 'admin' do

    get 'update',         :to => 'update#index'
    put 'update/update',  :to => 'update#update'

    resources :jobs do
      get 'calc',            :on => :collection
      get 'debug_calc',      :on => :collection
      get 'export',          :on => :collection
      get 'keys',            :on => :collection
      get 'wipe_out_time',   :on => :collection
      get 'wipe_out',        :on => :collection
      get 'wipe_out_points', :on => :collection
    end

    resource :import, :only => [:create]

    resources :users
  end


  ##############################
  # routes for setup

  ## todo: move to admin - why? why not?

  get 'setup',  :to => 'setup/bonus_rounds#index'

  namespace :setup do
    resources :bonus_rounds
  end


  #######################
  # home route
  
  root :to => 'pages#home'
end

ruby on rails/app/models/bonus_round.rb
# == Schema Information
#
# Table name: bonus_rounds
#
#  id         :integer         not null, primary key
#  pool_id    :integer         not null
#  title      :string(255)     not null
#  pos        :integer         not null
#  created_at :datetime        not null
#  updated_at :datetime        not null
#


BonusRound = SportDb::Model::BonusRound

ruby on rails/app/controllers/setup/base_controller.rb
class Setup::BaseController < ApplicationController
  
  layout 'setup'

  ## todo: add require_admin etc.  
  
end

ruby on rails/app/controllers/setup/bonus_rounds_controller.rb
## todo: move to admin ??? why - why not?

class Setup::BonusRoundsController < Setup::BaseController

  # GET /bonus_rounds
  def index
    @rounds = BonusRound.all
  end

  # GET /bonus_rounds/new
  def new
    @round = BonusRound.new
  end

  # POST /bonus_rounds
  def create
    @round = BonusRound.new(params[:bonus_round])

    if @round.save
      redirect_to bonus_rounds_path(), :notice => 'Runde erfolgreich gespeichert.' 
    else
      render :action => 'new'
    end
  end

  # GET /bonus_rounds/1/edit
  def edit
    @round = BonusRound.find(params[:id])
  end

  # PUT /bonus_rounds/1
  def update
    @round = BonusRound.find(params[:id])

    if @round.update_attributes(params[:bonus_round])
      redirect_to bonus_rounds_path(), :notice => 'Runde erfolgreich gespeichert.' 
    else
      render :action => 'edit'
    end
  end

  # DELETE /bonus_rounds/1
  def destroy
    @round = BonusRound.find(params[:id])
    @round.destroy

    redirect_to bonus_rounds_path()
  end

end # class BonusRoundsController

ruby on rails/app/views/setup/bonus_rounds/_form.html.erb
<%= form_for(@round, :as => :round, :url => @round.new_record? ? setup_bonus_rounds_path() : setup_bonus_round_path(@round) ) do |f| %>
  <% if @round.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@round.errors.count, "error") %> prohibited this round from being saved:</h2>

      <ul>
      <% @round.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
     <td></td>
     <td><!-- todo: add pool/event field w/ select box -->
         <!-- todo/fix: why does it now work?? -->
         <%#= @round.pool.full_title %>
     </td>
    </tr>
    <tr>
      <td><%= f.label :pos, 'Pos#:' %></td>
      <td><%= f.text_field :pos, size: '3' %></td>
    </tr>
    <tr>
      <td><%= f.label :title, 'Title:' %></td>
      <td><%= f.text_field :title %></td>
    </tr>
  </table>
  
  <div class="actions">
    <%= f.submit 'Save', :class => 'btn-primary' %>
    <%= link_to 'Back', setup_bonus_rounds_path(), :class => 'btn' %>
  </div>
<% end %>

ruby on rails/app/views/setup/bonus_rounds/edit.html.erb
<h1>Edit Bonus Round</h1>

<%= render 'form' %>

ruby on rails/app/views/setup/bonus_rounds/index.html.erb
<h1><%= BonusRound.count %> Bonus Rounds</h1>

<%= link_to 'New Bonus Round', new_setup_bonus_round_path(), :class => 'btn-primary' %>

<!-- todo: stack by pool -->

<table>
<% @rounds.each do |round| %>
   <tr>
     <td><%= round.pool.full_title %></td>
     <td>(<%= round.id %>)</td>
     <td>#<%= round.pos %></td>
     <td><%= round.title %></td>
     <td><%= link_to 'Edit', edit_setup_bonus_round_path( round ), :class => 'btn' %></td>
   </tr>
<% end %><!-- rounds.each -->
</table>

<p>
<%= link_to 'New Bonus Round', new_setup_bonus_round_path(), :class => 'btn-primary' %>
</p>

ruby on rails/app/views/setup/bonus_rounds/new.html.erb
<h1>New Bonus Round</h1>

<%= render 'form' %>