ruby on rails/config/routes.rb
Sportbook::Application.routes.draw do

  ####################
  # routs for db (using sportdb-admin rails engine)

  puts '[boot] routes.rb - before mount SportDbAdmin::Engine'
  mount SportDbAdmin::Engine, :at => '/db'
  puts '[boot] routes.rb - after mount SportDbAdmin::Engine'


  puts '[boot] routes.rb - before mount WorldDbAdmin::Engine'
  mount WorldDbAdmin::Engine, :at => '/worlddb'
  puts '[boot] routes.rb - after mount WorldDbAdmin::Engine'


  mount About::Server,     :at => '/sys'
  mount DbBrowser::Server, :at => '/browse'

  ## todo: add ActivityDb::Server too


  get 'signin',   :to => 'sessions#new'
  get 'signout',  :to => 'sessions#destroy'

  get 'about',    :to => 'pages#about'
  get 'home',     :to => 'pages#home'
  get 'style',    :to => 'pages#style'     # testpage for styles (css)

  get 'live',          :to => 'live#index'
  get 'live/:game_id', :to => 'live#show', :as => :live_game

  get 'time',             :to => 'time#index'
  get 'time2',            :to => 'time#index2'
  get 'time3',            :to => 'time#index3'   # old action timeline - obsolete remove/delete after cleanup!!
  get 'time4',            :to => 'time#index4'   # old action timeline - obsolete remove/delete after cleanup!!

  get 'ical/:play_id',   :to => 'ical#index'

  resource :session, :only => [:new, :create, :destroy]

  resource :password, :only => [:new, :create, :destroy]

  resources :profiles, :only => [:index, :show]

  resources :plays

  resources :pools do
    get 'add_player_to', :on => :member
    resources :players, :only => [:show, :edit]
  end

  #############
  # routes for admin

  get 'admin',  :to => 'admin/pools#index'
  
  namespace :admin do
    resources :pools

    # add plain text import forms for fixtures n quotes  
    resources :fixtures
    resources :quotes    
    
    get 'bonus',         :to => 'bonus#index'

    ## fix: post required?? double check!!
    get 'bonus/update',  :to => 'bonus#update'
  end

  ##############################
  # routes for admin via module (admin not in url -- todo/fix)
  
  scope :module => 'admin' do

    get 'update',         :to => 'update#index'
    put 'update/update',  :to => 'update#update'

    resources :jobs do
      get 'calc',            :on => :collection
      get 'debug_calc',      :on => :collection
      get 'export',          :on => :collection
      get 'keys',            :on => :collection
      get 'wipe_out_time',   :on => :collection
      get 'wipe_out',        :on => :collection
      get 'wipe_out_points', :on => :collection
    end

    resource :import, :only => [:create]

    resources :users
  end


  ##############################
  # routes for setup

  ## todo: move to admin - why? why not?

  get 'setup',  :to => 'setup/bonus_rounds#index'

  namespace :setup do
    resources :bonus_rounds
  end


  #######################
  # home route
  
  root :to => 'pages#home'
end

ruby on rails/app/controllers/live_controller.rb
# encoding: utf-8

class LiveController < ApplicationController

  def index
    
    limit = params[:limit] || '4'
    
    if params[:past].present? && ['1','t','true','yes', 'on'].include?( params[:past] )
      # find last past games
      @games = Game.where( 'play_at < ?', Time.now).order( 'play_at desc').limit( limit )
    else
      # find next upcoming games
      @games = Game.where( 'play_at > ?', Time.now ).order( 'play_at').limit( limit )
    end

    @show_tips = (params[:tips].present? && ['1','t','true','yes', 'on'].include?( params[:tips] ))
  end
  
  def show
    @game =  Game.find( params[:game_id] )
  end
    
end # class LiveController

ruby on rails/app/views/live/_game.html.erb
  <table class='live'>
    <tr>
      <td><%= game.play_at.strftime('%H:%M') %></td>
      <td style='min-width: 360px; text-align: right;'>
  <span class='<%= game.team1_style_class %>'>
    <span style='font-size: 160%;'><%= game.team1.title %></span>
  </span>
      <%= logo_for_team( game.team1 ) %>
      </td>
      <td>
        <span style='font-size: 160%;'><%= game.score_str %></span>
      </td>
    <td>
    <%= logo_for_team( game.team2 ) %>
    <span class='<%= game.team2_style_class %>'>
      <span style='font-size: 160%;'><%= game.team2.title %></span>
    </span>
    </td>
    <td>
      (<%= game.round.event.title %> / <%= game.round.title %>)
    </td>
  </table>


<table>
 <tr>
  <td><!-- begin column 1 -->
<% if game.complete_tips.count > 0 %>

<table style='border: 1px solid silver;' cellspacing='0' cellpadding='6px'>
  <tr style='text-align: center; background-color: silver;'>
    <td style='min-width: 250px;'>1</td>
    <td style='min-width: 250px;'>X</td>
    <td style='min-width: 250px;'>2</td>
    <td></td>
  </tr>
  <tr style='text-align: center;'>
    <td><span class='larger <%= game.tip_1_style_class %>'><%= game.tip_1_count %></span></td>
    <td><span class='larger <%= game.tip_x_style_class %>'><%= game.tip_x_count %></span></td>
    <td><span class='larger <%= game.tip_2_style_class %>'><%= game.tip_2_count %></span></td>
    <td><span class='smaller'>(<%= game.tip_12x_count %> Tipps)</span></td>
  </tr>
  <tr style='text-align: center;'>
    <td><span class='larger <%= game.tip_1_style_class %>'>
           <%= (game.tip_1_count*100/game.tip_12x_count) %>%
        </span>
    </td>
    <td><span class='larger <%= game.tip_x_style_class %>'>
          <%= (game.tip_x_count*100/game.tip_12x_count) %>%
        </span>
    </td>
    <td><span class='larger <%= game.tip_2_style_class %>'>
        <%= (game.tip_2_count*100/game.tip_12x_count) %>%
       </span>
    </td>
  </tr>
</table>

<% end %><!-- if game.complete_tips.count > 0 -->
  </td><!-- end column 1 -->
  <td><!-- begin column 2 -->

    <table class='odds'>
      <tr>
        <td>1</td>
        <td>X</td>
        <td>2</td>
        <td></td>
      </tr>

<% game.quotes.each do |quote| %>
<tr>
  <td><%= fmt_quote( quote.odds1 ) %></td>
  <td><%= fmt_quote( quote.oddsx ) %></td>
  <td><%= fmt_quote( quote.odds2 ) %></td>
  <td>(<%= quote.service.title %>)</td>
    <!-- add last updated? -->
</tr>
<% end %>

     </table>
  
  </td><!-- end column 2 -->
 </tr>
</table>

ruby on rails/app/views/live/_game_tips.html.erb
<% if game.complete_tips.count > 0 %>

<table cellspacing=0>
  <tr>
    <!-- left -->
    <td style='min-width: 250px;'>
      <ul class='none'>
         <% game.complete_tips_1.each do |tip| %>
            <li>
              <span class='<%= tip.bingo_style_class %>'>
                <%= tip.public_score_str %>
              </span>
              <span class='<%= hl_style_for_user(tip.user) %>'>
                <%= tip.public_user_name_str %>
              </span>
            </li>
         <% end %>
      </ul>
    </td>
    <!-- middle -->
    <td style='min-width: 250px;'>
      <ul class='none'>
         <% game.complete_tips_x.each do |tip| %>
            <li>
              <span class='<%= tip.bingo_style_class %>'>
                <%= tip.public_score_str %>
              </span>
              <span class='<%= hl_style_for_user(tip.user) %>'>
                <%= tip.public_user_name_str %>
              </span>
            </li>
         <% end %>
      </ul>
    </td>
    <!-- right -->
    <td style='min-width: 250px;'>
      <ul class='none'>
         <% game.complete_tips_2.each do |tip| %>
            <li>
              <span class='<%= tip.bingo_style_class %>'>
                <%= tip.public_score_str %>
              </span>
              <span class='<%= hl_style_for_user(tip.user) %>'>
                <%= tip.public_user_name_str %>
              </span>
            </li>
         <% end %>
      </ul>
    </td>
  </tr>
</table>

<% end %><!-- if game.complete_tips.count > 0 -->


<% if game.incomplete_tips.count > 0 %>
<p><!-- <%= game.incomplete_tips.count %>--> Ungültige Tipps</p>

<table>
  <% game.incomplete_tips.each do |tip| %>
    <tr>
      <td>
       <%= "(#{tip.toto12x})" if tip.toto12x  %>
      </td>
      <td style='text-align: center;'>
        <span class='<%= tip.bingo_style_class %>'>
         <%= tip.score_str %>
        </span>
      </td>
      <td>
         <span class='<%= hl_style_for_user(tip.user) %>'>
           <%= tip.user.name %>
         </span>
      </td>
    </tr>
  <% end %><!-- each tip -->
</table>
<% end %><!-- if game.incomplete_tips.count > 0  -->

ruby on rails/app/views/live/index.html.erb
<% content_for :breadcrumb do %>
  <%= link_to 'Wettpools', pools_path() %> ›
   Live
<% end %>

<%  last_play_at = Time.local( 1999, 1, 1 )
    @games.each do |game| %>

  <% unless last_play_at.year   == game.play_at.year  &&
            last_play_at.month  == game.play_at.month &&
            last_play_at.day    == game.play_at.day %>
        
    <h2><%= game.play_at.strftime('%A, %d. %B %Y') %></h2>
        
  <% end %>
  

  <%= render partial: 'game', locals: { game: game } %>
  
  <% if @show_tips %>
    <%= render partial: 'game_tips', locals: { game: game } %>
  <% end %>
  
<% last_play_at = game.play_at
   end %><!-- each game -->

ruby on rails/app/views/live/show.html.erb
<% content_for :breadcrumb do %>
  <%= link_to 'Wettpools', pools_path() %> ›
   Live <%= "#{@game.team1.title} - #{@game.team2.title}" %>
<% end %>


  <h2><%= @game.play_at.strftime('%A, %d. %B %Y') %></h2>

<%= render partial: 'game', locals: { game: @game } %>
  
<%= render partial: 'game_tips', locals: { game: @game } %>