ruby on rails/config/routes.rb
Sportbook::Application.routes.draw do

  ####################
  # routs for db (using sportdb-admin rails engine)

  puts '[boot] routes.rb - before mount SportDbAdmin::Engine'
  mount SportDbAdmin::Engine, :at => '/db'
  puts '[boot] routes.rb - after mount SportDbAdmin::Engine'


  puts '[boot] routes.rb - before mount WorldDbAdmin::Engine'
  mount WorldDbAdmin::Engine, :at => '/worlddb'
  puts '[boot] routes.rb - after mount WorldDbAdmin::Engine'


  mount About::Server,     :at => '/sys'
  mount DbBrowser::Server, :at => '/browse'

  ## todo: add ActivityDb::Server too


  get 'signin',   :to => 'sessions#new'
  get 'signout',  :to => 'sessions#destroy'

  get 'about',    :to => 'pages#about'
  get 'home',     :to => 'pages#home'
  get 'style',    :to => 'pages#style'     # testpage for styles (css)

  get 'live',          :to => 'live#index'
  get 'live/:game_id', :to => 'live#show', :as => :live_game

  get 'time',             :to => 'time#index'
  get 'time2',            :to => 'time#index2'
  get 'time3',            :to => 'time#index3'   # old action timeline - obsolete remove/delete after cleanup!!
  get 'time4',            :to => 'time#index4'   # old action timeline - obsolete remove/delete after cleanup!!

  get 'ical/:play_id',   :to => 'ical#index'

  resource :session, :only => [:new, :create, :destroy]

  resource :password, :only => [:new, :create, :destroy]

  resources :profiles, :only => [:index, :show]

  resources :plays

  resources :pools do
    get 'add_player_to', :on => :member
    resources :players, :only => [:show, :edit]
  end

  #############
  # routes for admin

  get 'admin',  :to => 'admin/pools#index'
  
  namespace :admin do
    resources :pools

    # add plain text import forms for fixtures n quotes  
    resources :fixtures
    resources :quotes    
    
    get 'bonus',         :to => 'bonus#index'

    ## fix: post required?? double check!!
    get 'bonus/update',  :to => 'bonus#update'
  end

  ##############################
  # routes for admin via module (admin not in url -- todo/fix)
  
  scope :module => 'admin' do

    get 'update',         :to => 'update#index'
    put 'update/update',  :to => 'update#update'

    resources :jobs do
      get 'calc',            :on => :collection
      get 'debug_calc',      :on => :collection
      get 'export',          :on => :collection
      get 'keys',            :on => :collection
      get 'wipe_out_time',   :on => :collection
      get 'wipe_out',        :on => :collection
      get 'wipe_out_points', :on => :collection
    end

    resource :import, :only => [:create]

    resources :users
  end


  ##############################
  # routes for setup

  ## todo: move to admin - why? why not?

  get 'setup',  :to => 'setup/bonus_rounds#index'

  namespace :setup do
    resources :bonus_rounds
  end


  #######################
  # home route
  
  root :to => 'pages#home'
end

ruby on rails/app/controllers/admin/bonus_controller.rb
class Admin::BonusController < Admin::BaseController

  def index
    @pools = Pool.all
  end
  
  def update
    # mass update of bonus tips 
     
    # check for case w/ no games
    if params[:tips]
     
      pp params[:tips]
     
      params[:tips].each do |tip_id,tip_hash|
        tip = BonusTip.find( tip_id )
      
        # only update if has changes (to avoid duplicate/false action item in news feed)
      
        pts = tip_hash[:pts].blank? ? 0 : tip_hash[:pts].to_i
      
        if tip.pts != pts
          logger.info "*** updating bonus tip #{tip_id} (pts: #{pts})"

          tip.pts = pts
          tip.save!
        else
          logger.info "*** skip updating bonus tip #{tip_id} - no changes"
        end
      end # each tip
      flash[:success] = 'Bonuspunkte erfolgreich gespeichert.'
    end  # tips.present?
  
    redirect_to admin_bonus_path()
  end

end # class BonusController

ruby on rails/app/views/admin/bonus/index.html.erb
<% @pools.each do |pool| %>
<h2><%= pool.full_title %></h2>
 <% pool.bonus_rounds.each do |round| %>
   <h3><%= round.title %></h3>
   <% round.questions.each do |question| %>
     <h4>Q: <%= question.title %></h4>
      <%= form_for 'bonus', :url => admin_bonus_update_path(), :html => { :method => 'put' } do |f| %>
      <table>
     <% question.tips.each do |tip| %>
      <tr>
        <td><%= tip.user.name %></td>
        <td>
         <%= fields_for 'tips[]', tip do |ff| %>
           <%= ff.hidden_field :id %>
           <%= ff.text_field :pts, :size => 1 %>
         <% end %><!-- fields_for tips[] -->
         Punkte
        </td>
      </tr>
     <% end %><!-- each tip -->
      </table>
       <p>
        <%= f.submit "Update '#{question.title}'", :class => 'btn-primary' %>
       </p>
      <% end %><!-- form bonus -->
   <% end %><!-- each question -->
 <% end %><!-- each round -->
<% end %><!-- each pool -->