ruby on rails/config/routes.rb
Sportbook::Application.routes.draw do

  ####################
  # routs for db (using sportdb-admin rails engine)

  puts '[boot] routes.rb - before mount SportDbAdmin::Engine'
  mount SportDbAdmin::Engine, :at => '/db'
  puts '[boot] routes.rb - after mount SportDbAdmin::Engine'


  puts '[boot] routes.rb - before mount WorldDbAdmin::Engine'
  mount WorldDbAdmin::Engine, :at => '/worlddb'
  puts '[boot] routes.rb - after mount WorldDbAdmin::Engine'


  mount About::Server,     :at => '/sys'
  mount DbBrowser::Server, :at => '/browse'

  ## todo: add ActivityDb::Server too


  get 'signin',   :to => 'sessions#new'
  get 'signout',  :to => 'sessions#destroy'

  get 'about',    :to => 'pages#about'
  get 'home',     :to => 'pages#home'
  get 'style',    :to => 'pages#style'     # testpage for styles (css)

  get 'live',          :to => 'live#index'
  get 'live/:game_id', :to => 'live#show', :as => :live_game

  get 'time',             :to => 'time#index'
  get 'time2',            :to => 'time#index2'
  get 'time3',            :to => 'time#index3'   # old action timeline - obsolete remove/delete after cleanup!!
  get 'time4',            :to => 'time#index4'   # old action timeline - obsolete remove/delete after cleanup!!

  get 'ical/:play_id',   :to => 'ical#index'

  resource :session, :only => [:new, :create, :destroy]

  resource :password, :only => [:new, :create, :destroy]

  resources :profiles, :only => [:index, :show]

  resources :plays

  resources :pools do
    get 'add_player_to', :on => :member
    resources :players, :only => [:show, :edit]
  end

  #############
  # routes for admin

  get 'admin',  :to => 'admin/pools#index'
  
  namespace :admin do
    resources :pools

    # add plain text import forms for fixtures n quotes  
    resources :fixtures
    resources :quotes    
    
    get 'bonus',         :to => 'bonus#index'

    ## fix: post required?? double check!!
    get 'bonus/update',  :to => 'bonus#update'
  end

  ##############################
  # routes for admin via module (admin not in url -- todo/fix)
  
  scope :module => 'admin' do

    get 'update',         :to => 'update#index'
    put 'update/update',  :to => 'update#update'

    resources :jobs do
      get 'calc',            :on => :collection
      get 'debug_calc',      :on => :collection
      get 'export',          :on => :collection
      get 'keys',            :on => :collection
      get 'wipe_out_time',   :on => :collection
      get 'wipe_out',        :on => :collection
      get 'wipe_out_points', :on => :collection
    end

    resource :import, :only => [:create]

    resources :users
  end


  ##############################
  # routes for setup

  ## todo: move to admin - why? why not?

  get 'setup',  :to => 'setup/bonus_rounds#index'

  namespace :setup do
    resources :bonus_rounds
  end


  #######################
  # home route
  
  root :to => 'pages#home'
end

ruby on rails/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer         not null, primary key
#  name            :string(255)     not null
#  email           :string(255)     not null
#  password_digest :string(255)
#  key             :string(255)     not null
#  admin           :boolean         default(FALSE), not null
#  guest           :boolean         default(FALSE), not null
#  active          :boolean         default(TRUE), not null
#  created_at      :datetime        not null
#  updated_at      :datetime        not null
#

module SportDb
  module Model

## NB: extend from sport.db-play gem

class User
  
  has_many :actions
  
  has_secure_password   # use built-in rails macro for password to password_digest machinery

  before_save :on_before_save
  
  def on_before_save
    if email.blank?
      self.key = ''
    else
      ## remove whitespace and (.-+_) and downcase
      self.key = email.gsub( /[\s\.\-+_]/, '' ).downcase
    end
  end
  
  def self.create_from_ary!( users )
    users.each do |values|
      
      attr = {
        :name     => values[0],
        :email    => values[1],
        :password => 'tipp'
      }

      ## check for optional values
      opts = values[2] 
      if opts
        attr[ :admin ] = opts[ :admin ]  if opts.has_key?( :admin )
        attr[ :guest ] = opts[ :guest ]  if opts.has_key?( :guest )
      end
      
      User.create!( attr )
    end # each user
  end

end  # class User

  end # module Model
end  # module SportDb

User = SportDb::Model::User

ruby on rails/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController

  # GET /users
  def index
    @users = User.all
  end

 # GET /users/new
  def new
    @user = User.new
  end

  # POST /users
  def create
    @user = User.new(params[:user])
    @user.password = 'tipp'   # default password change later

    if @user.save
      redirect_to users_path(), notice: 'Benutzer erfolgreich gespeichert.' 
    else
      render action: 'new'
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # PUT /users/1
  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to users_path(), notice: 'Benutzer erfolgreich gespeichert.' 
    else
      render action: 'edit' 
    end
  end

  # GET /users/1
  def show
    @user = User.find(params[:id])
  end

  # DELETE /users/1
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    redirect_to users_path() 
  end
  
end # class UsersController

ruby on rails/app/views/admin/users/_form.html.erb
<%= form_for(@user, :as => :user, :url => @user.new_record? ? users_path() : user_path(@user) ) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
 
  <table>
    <tr>
      <td><%= f.label :name, 'Name:' %></td>
      <td><%= f.text_field :name, 'data-autofocus' => 'true' %></td>
    </tr>
    <tr>
      <td><%= f.label :email, 'Email:' %></td>
      <td><%= f.text_field :email %></td>
    </tr>
    <tr>
      <td><%= f.label :active, 'Active Flag:' %></td>
      <td>
        <%= f.radio_button :active, 'true'  %><%= f.label :active_true, 'Ja' %>
        <%= f.radio_button :active, 'false' %><%= f.label :active_false, 'Nein' %>
      </td>
    </tr>
  </table>
  
  <div class="actions">
    <%= f.submit 'Speichern', :class => 'btn-primary' %>
    <%= link_to 'Zurück', users_path(), :class => 'btn' %>
  </div>
<% end %>

ruby on rails/app/views/admin/users/edit.html.erb
<h1>Benutzer</h1>

<%= render 'form' %>

ruby on rails/app/views/admin/users/index.html.erb
<h1><%= User.count %> Benutzer</h1>

<%= link_to 'Neuer Benutzer', new_user_path(), :class => 'btn-primary' %>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th>Key</th>
    <th>Flags</th>
    <th><!-- Edit --></th>
    <th><!-- Delete --></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to user.name, user_path(user) %></td>
    <td><%= user.email %></td>
    <td><%= user.key %></td>
    <td>
      <%= user.active? ? '(Active Flag)' : '' %>
      <%= user.admin? ? '(Admin Flag)' : '' %>
    </td>
    <td><%= link_to 'Bearbeiten', edit_user_path(user), :class => 'btn' %></td>
    <td><%= link_to 'Löschen', user_path(user), :confirm => 'Sicher?', :method =>'delete', :class => 'btn' %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Neuer Benutzer', new_user_path(), :class => 'btn-primary' %>

ruby on rails/app/views/admin/users/new.html.erb
<h1>Neuer Benutzer</h1>

<%= render 'form' %>

ruby on rails/app/views/admin/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>